language: objective-c
os: osx
osx_image: xcode9.3beta

env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=macOS
    - TEST_TYPE=tvOS
-before_install:
 - |
    gem install xcpretty -N --no-ri --no-rdoc
script:
- |
    ./setup.sh
    if [ "$TEST_TYPE" = iOS ]; then
      set -o pipefail
      xcodebuild clean test -workspace Kingfisher.xcworkspace -scheme Kingfisher -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' -enableCodeCoverage YES | xcpretty
    elif [ "$TEST_TYPE" = macOS ]; then
      set -o pipefail
      xcodebuild clean test -workspace Kingfisher.xcworkspace -scheme Kingfisher-macOS -enableCodeCoverage YES | xcpretty
    elif [ "$TEST_TYPE" = tvOS ]; then
      set -o pipefail
      xcodebuild clean test -workspace Kingfisher.xcworkspace -scheme Kingfisher-tvOS -destination "platform=tvOS Simulator,name=Apple TV" -enableCodeCoverage YES | xcpretty
    fi
after_success:
    - sleep 5
    - if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = macOS ] || [ "$TEST_TYPE" = tvOS ]; then
        bash <(curl -s https://codecov.io/bash)
      fi
