language: swift
osx_image: xcode10.1

cache: bundler

matrix:
  include:
  - name: iOS | Swift 4.2
    env: LANE=test_ci SCHEME=Kingfisher SWIFT_VERSION=4.2
  - name: macOS | Swift 4.2
    env: LANE=test_ci SCHEME=Kingfisher-macOS SWIFT_VERSION=4.2
  - name: tvOS | Swift 4.2
    env: LANE=test_ci SCHEME=Kingfisher-tvOS SWIFT_VERSION=4.2
  - name: iOS | Swift 4.0
    env: LANE=test_ci SCHEME=Kingfisher SWIFT_VERSION=4.0
  - name: macOS | Swift 4.0
    env: LANE=test_ci SCHEME=Kingfisher-macOS SWIFT_VERSION=4.0
  - name: tvOS | Swift 4.0
    env: LANE=test_ci SCHEME=Kingfisher-tvOS SWIFT_VERSION=4.0

script:
  - bundle exec fastlane $LANE
